version: "3.7"
services:
  postgres:
    image: postgres:11
    networks:
      - airflow-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  airflow:
    image: puckel/docker-airflow:1.10.4
    container_name: airflow
    build: .
    command: webserver
    networks:
      - airflow-net
    user: root # for DockerOperator
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./dags:/usr/local/airflow/dags
      - ./entrypoint.sh:/entrypoint.sh # override entrypoint
      - /var/run/docker.sock:/var/run/docker.sock # for DockerOperator
    ports:
      - 8080:8080
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/config/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  airflow-net:
    name: airflow-network
